# Generated by Django 2.0.2 on 2018-03-27 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('npcs', '0001_initial'),
        ('core', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usernpcs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='npcrace',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Group'),
        ),
        migrations.AddField(
            model_name='npcrace',
            name='languages',
            field=models.ManyToManyField(to='core.Language'),
        ),
        migrations.AddField(
            model_name='npcrace',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Size'),
        ),
        migrations.AddField(
            model_name='npcrace',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='npcklass',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='npcattributes',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='npc',
            name='alignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Alignment'),
        ),
        migrations.AddField(
            model_name='npc',
            name='attributes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npcs.NpcAttributes'),
        ),
        migrations.AddField(
            model_name='npc',
            name='descriptions',
            field=models.ManyToManyField(to='npcs.NpcDescription'),
        ),
        migrations.AddField(
            model_name='npc',
            name='klass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npcs.NpcKlass'),
        ),
        migrations.AddField(
            model_name='npc',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npcs.NpcRace'),
        ),
        migrations.AddField(
            model_name='npc',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='npc',
            name='users',
            field=models.ManyToManyField(through='npcs.UserNpcs', to=settings.AUTH_USER_MODEL),
        ),
    ]
